services:
  django:
    build:
      context: ./basic-contents-model
    container_name: django
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./basic-contents-model:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "8000"

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/var/www/static
      - media_volume:/var/www/media
    depends_on:
      - django

