services:
  django:
    build:
      context: ./basic-contents-model
    container_name: django
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./basic-contents-model:/app
    expose:
      - "8000"

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - django