# Generated by Django 4.2.20 on 2025-05-13 01:33

from django.db import migrations, models
import django.db.models.deletion
import djforms.fields.multiselectfield
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="제출일"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="IP 주소")),
                ("user_agent", models.TextField(verbose_name="User Agent")),
            ],
            options={
                "verbose_name": "폼 응답",
                "verbose_name_plural": "폼 응답 목록",
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="FormTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="제목")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="생성일"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="수정일"),
                ),
                (
                    "expires_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="만료일"),
                ),
                (
                    "allow_anonymous",
                    models.BooleanField(default=False, verbose_name="익명 제출 허용"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="활성화")),
            ],
            options={
                "verbose_name": "폼",
                "verbose_name_plural": "폼 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FormTemplateField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "단답형"),
                            ("textarea", "장문형"),
                            ("radio", "객관식"),
                            ("checkbox", "체크박스"),
                            ("select", "드롭다운"),
                            ("file", "파일 업로드"),
                            ("rating", "등급"),
                        ],
                        default="text",
                        max_length=50,
                        verbose_name="필드 타입",
                    ),
                ),
                (
                    "question",
                    models.CharField(blank=True, max_length=1000, verbose_name="질문"),
                ),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("required", models.BooleanField(default=False, verbose_name="필수")),
                ("choices", models.TextField(blank=True, verbose_name="선택지")),
                (
                    "file_types",
                    djforms.fields.multiselectfield.MultiSelectField(
                        blank=True,
                        choices=[
                            ("pdf", "PDF"),
                            ("jpg", "JPG"),
                            ("png", "PNG"),
                            ("gif", "GIF"),
                            ("txt", "TXT"),
                            ("csv", "CSV"),
                            ("xlsx", "XLSX"),
                            ("docx", "DOCX"),
                            ("pptx", "PPTX"),
                            ("all", "All Files"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="허용 파일 형식",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="순서"),
                ),
                (
                    "form_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_set",
                        to="djforms.formtemplate",
                        verbose_name="폼",
                    ),
                ),
            ],
            options={
                "verbose_name": "폼 필드",
                "verbose_name_plural": "폼 필드 목록",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="FormResponseField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(verbose_name="값")),
                (
                    "file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="form_responses/",
                        verbose_name="파일",
                    ),
                ),
                (
                    "form_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_set",
                        to="djforms.formresponse",
                        verbose_name="응답",
                    ),
                ),
                (
                    "form_template_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response_set",
                        to="djforms.formtemplatefield",
                        verbose_name="필드",
                    ),
                ),
            ],
            options={
                "verbose_name": "응답 필드",
                "verbose_name_plural": "응답 필드 목록",
            },
        ),
        migrations.AddField(
            model_name="formresponse",
            name="form_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="response_set",
                to="djforms.formtemplate",
                verbose_name="폼",
            ),
        ),
    ]
