# Generated by Django 4.2.20 on 2025-04-08 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basiccontent', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainpost',
            name='post_type',
        ),
        migrations.AddField(
            model_name='subpost',
            name='post_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='basiccontent.posttype', verbose_name='글 유형'),
            preserve_default=False,
        ),
    ]
