# Generated by Django 4.2.20 on 2025-04-17 05:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basiccontent', '0002_remove_mainpost_post_type_subpost_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='전화번호는 000-0000-0000 형식이어야 합니다.', regex='^\\d{3}-\\d{4}-\\d{4}$')])),
                ('birthday', models.DateField()),
                ('gender', models.CharField(choices=[('M', '남'), ('F', '여')], max_length=10, verbose_name='성별')),
            ],
            options={
                'verbose_name': '유저',
            },
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': '컨텐츠 기록 모델'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': '파일 컨텐츠'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': '이미지 컨텐츠'},
        ),
        migrations.AlterModelOptions(
            name='mainpost',
            options={'verbose_name': '메인 글'},
        ),
        migrations.AlterModelOptions(
            name='postcontent',
            options={'verbose_name': '글에 넣을 컨텐츠'},
        ),
        migrations.AlterModelOptions(
            name='postoptions',
            options={'verbose_name': '객관식 보기'},
        ),
        migrations.AlterModelOptions(
            name='posttype',
            options={'verbose_name': '글 유형'},
        ),
        migrations.AlterModelOptions(
            name='subpost',
            options={'verbose_name': '실제 문항'},
        ),
        migrations.AlterModelOptions(
            name='text',
            options={'verbose_name': '텍스트 컨텐츠'},
        ),
        migrations.AddField(
            model_name='subpost',
            name='necessary',
            field=models.BooleanField(default=True, verbose_name='필수 여부'),
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjective_answer', models.TextField(blank=True, null=True, verbose_name='주관식 답변')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basiccontent.postoptions', verbose_name='답변')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basiccontent.subpost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basiccontent.user')),
            ],
            options={
                'verbose_name': '유저 답안',
            },
        ),
        migrations.CreateModel(
            name='MultiSubjectiveAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_number', models.PositiveIntegerField(verbose_name='답안번호')),
                ('answer_description', models.TextField(blank=True, null=True, verbose_name='답안')),
                ('user_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basiccontent.useranswer')),
            ],
            options={
                'verbose_name': '다중답안 저장용',
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_time', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=50)),
                ('ip_address', models.GenericIPAddressField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basiccontent.user')),
            ],
            options={
                'verbose_name': '유저 접근 기록',
            },
        ),
    ]
