# Generated by Django 4.2.20 on 2025-04-22 05:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('basiccontent', '0003_user_alter_content_options_alter_file_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(verbose_name='생년월일'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='전화번호는 000-0000-0000 형식이어야 합니다.', regex='^\\d{3}-\\d{4}-\\d{4}$')], verbose_name='전화번호'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='이름'),
        ),
        migrations.CreateModel(
            name='SurveyLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('main_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basiccontent.mainpost')),
            ],
            options={
                'verbose_name': '설문 링크',
            },
        ),
    ]
