# Generated by Django 4.2.20 on 2025-04-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basiccontent', '0005_alter_user_phone_number_alter_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='설문 완료 여부'),
        ),
    ]
